# Generated by Django 3.2.15 on 2023-02-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, verbose_name='チャンネル名')),
                ('caption', models.TextField(verbose_name='キャプション')),
                ('video_url', models.URLField(max_length=255, verbose_name='動画URL')),
                ('music_name', models.CharField(max_length=255, verbose_name='曲名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿',
            },
        ),
    ]
